server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ntt-data-challenge-accounts
spring:
  application:
    name: ntt-data-challenge-accounts
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/ntt-data-challenge"
    username: postgress
    password: password
    show-sql: true
logging:
  level:
    ec:
      dev:
        samagua:
          ntt_data_challenge_accounts: DEBUG

ntt-data-challenge-clients:
  url: http://localhost:8762/ntt-data-challenge-clients/api
