server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ntt-data-challenge-accounts
spring:
  application:
    name: ntt-data-challenge-accounts
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/ntt-data-challenge-accounts"
    username: postgres
    password: password
    show-sql: true
